language: python
cache: pip
dist: xenial
matrix:
    fast_finish: true
    include:
      - { python: "3.6", env: DJANGO=2.2 }
      - { python: "3.6", env: DJANGO=3.0 }
      - { python: "3.6", env: DJANGO=3.1 }
      - { python: "3.6", env: DJANGO=master }

      - { python: "3.7", env: DJANGO=2.2 }
      - { python: "3.7", env: DJANGO=3.0 }
      - { python: "3.7", env: DJANGO=3.1 }
      - { python: "3.7", env: DJANGO=master }

      - { python: "3.8", env: DJANGO=2.2 }
      - { python: "3.8", env: DJANGO=3.0 }
      - { python: "3.8", env: DJANGO=3.1 }
      - { python: "3.8", env: DJANGO=master }

      - { python: "3.9", env: DJANGO=2.2 }
      - { python: "3.9", env: DJANGO=3.0 }
      - { python: "3.9", env: DJANGO=3.1 }
      - { python: "3.9", env: DJANGO=master }

      - { python: "3.9", env: TOXENV=coverage }
      - { python: "3.9", env: TOXENV=lint }
      - { python: "3.9", env: TOXENV=docs }

    allow_failures:
      - env: DJANGO=master

install:
    - pip install tox tox-venv tox-travis

script:
    - tox

notifications:
    email: false
