name: PyNotify Setup
description: Prepares PyNotify development environment.

inputs:
    python-version:
        required: true
        default: '3.9'
    django-version:
        required: true
        default: '3.2.*'

runs:
    using: 'composite'
    steps:
        - uses: actions/setup-python@v2
          with:
              python-version: ${{ inputs.python-version }}

        - shell: bash
          run: |
              sudo apt-get install -y gettext libxml2-dev libxslt-dev
              python -m pip install django==${{ inputs.django-version }}
              make develop
