# Generated by Django 2.2 on 2022-01-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pynotify', '0007_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotificationtemplate',
            name='extra_fields',
            field=models.TextField(blank=True, null=True, verbose_name='extra fields'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='extra_fields',
            field=models.TextField(blank=True, null=True, verbose_name='extra fields'),
        ),
        migrations.AlterField(
            model_name='adminnotificationtemplate',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='is locked'),
        ),
    ]
