# Generated by Django 3.2.11 on 2022-01-17 06:49

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pynotify', '0007_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotificationtemplate',
            name='extra_fields',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True,
                                   verbose_name='extra fields'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='extra_fields',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True,
                                   verbose_name='extra fields'),
        ),
        migrations.AlterField(
            model_name='adminnotificationtemplate',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='is locked'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True,
                                   verbose_name='extra data'),
        ),
    ]
