name: PyNotify CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ['3.8', '3.9']
            django-version: ['3.1.*', '3.2.*']
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/workflows/setup
              with:
                  python-version: ${{ matrix.python-version }}
                  django-version: ${{ matrix.django-version }}
            - run: make test

    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/workflows/setup
            - run: make coverage
            - uses: coverallsapp/github-action@master
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                path-to-lcov: 'coverage.lcov'

    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/workflows/setup
            - run: make docs
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/workflows/setup
            - run: make lint
